### Requêtes à envoyer avec l'extension Rest Client


### ===========================
# User
### ===========================


### POST /auth/register
POST http://localhost:3050/auth/register HTTP/1.1
content-type: application/json

{
  "username": "Alice",
  "email": "alice@mail.io",
  "password": "Azertyuiop1234"
}

### POST /auth/login
# @name login
POST http://localhost:3050/auth/login HTTP/1.1
content-type: application/json

{
  "email": "alice@mail.io",
  "password": "Azertyuiop1234"
}

### POST /auth/logout
@authToken = {{login.response.body.token}}

POST http://localhost:3050/auth/logout HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}